---
gamecraft_version: 0.2.0-1
gamecraft_image: micktwomey/gamecraft:{{gamecraft_version}}
gamecraft_links: postgresql:postgresql,memcached:memcached
gamecraft_volumes: /gamecraft/config:/gamecraft/config,/gamecraft/logs:/gamecraft/logs,/gamecraft/uploads:/gamecraft/uploads,/gamecraft/backups:/gamecraft/backups
